sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t rmrjaiswal/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rmrjaiswal/react-test npm test

after_success:
  - docker build -t rmrjaiswal/multi-client ./client
  - docker build -t rmrjaiswal/multi-nginx ./nginx
  - docker build -t rmrjaiswal/multi-server ./server
  - docker build -t rmrjaiswal/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push rmrjaiswal/multi-client
  - docker push rmrjaiswal/multi-nginx
  - docker push rmrjaiswal/multi-server
  - docker push rmrjaiswal/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'ca-central-1'
  app: 'multi-docker'
  env: 'Multi-docker-env'
  bucket_name: 'elasticbeanstalk-ca-central-1-545362484401'
  bucket_path: 'multi-docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
